### ISSUE TITLE
[feat-request] Support Sveltekit?

### ISSUE THREAD

**Issue by benbender** [PabloSzx/graphql-ez#146]
I was poking around with [sveltekit](https://kit.svelte.dev/) lateley and liked it very much. So I was asking myself if there are any plans to support it in graphql-ez? 

The interesting/complicated part of this effort would be that sveltekit does much of the work as a vite-compiler-plugin beforehand and therefor the exposed request/response-objects are quite limited (at least atm) and a bit unusual...

**Comment by PabloSzx** [comment]
Hi, I'm very aware of the sveltekit and I also think that it would be very nice to add integration, but at the same time, a quick look at the docs I wasn't able to find a Next.js API Routes equivalent, and it seems to work with server adapters, but I'm not 100% in the loop of how everything works there

**Comment by benbender** [comment]
It has two concepts which are interesting here: [Endpoints](https://kit.svelte.dev/docs#routing-endpoints) which are a bit like nextjs-api-routes and a [hook](https://kit.svelte.dev/docs#routing-endpoints) which runs before every request and is intended to modify the request.

Problem though is that the request-object is quite limited and there is no real response-object anywhere - they only return a JSON-structure with status, body and headers. 

I would assume that the request-object is sufficient for most cases, but I can't estimate the impact of the missing response-object. That's why I didn't give it a shot initially and opened the issue instead....

**Comment by PabloSzx** [comment]
It should be possible to make an adapter, but most of the current plugins wouldn't work out of the box with it, since the request is not an extension of HTTP's IncomingMessage, but I would guess that most of the setup for the integration would be relatively similar to the Next.js one, but with the plugin logic adapted to the return-only logic of sveltekit endpoints

**Comment by PabloSzx** [comment]
The types incompatibility doesn't mean it's not possible to make another version of the types that are not constrained to Node.js HTTP's, since that also might add compatibility for other integrations like cloudflare workers

**Comment by benbender** [comment]
I thought the same - but couldn't estimate if it would be worth the effort or if it would be plain easier to just go for `graphql-helix` and graphiql/altair if most of the plugins won't work anyways.

**Comment by PabloSzx** [comment]
Not all the EZ plugins are http related plugins, some are schema/context related, and those should not have any issue working with this more "vanilla" version of graphql-ez, I think there still would be some value in there

**Comment by jycouet** [comment]
Well done guys!
I came across Ez, and it's really Ez!!! ✨

I managed to put graphiql, voyager and modules in a nice way 👍
Do you have a list of plugins ready for SvelteKit? Would be nice to have it in the doc somewhere?

**Comment by PabloSzx** [comment]
> Well done guys! I came across Ez, and it's really Ez!!! ✨
> 
> I managed to put graphiql, voyager and modules in a nice way 👍 Do you have a list of plugins ready for SvelteKit? Would be nice to have it in the doc somewhere?

You can go to https://www.graphql-ez.com/plugins and press `sveltekit` tag, which will filter all the sveltekit compatible plugins

**Comment by jycouet** [comment]
Thx @PabloSzx for the hint 👍
As I like a lot the lib, I spend a bit of time on it.

In the plugin order:
 - ❌ Altair GraphQL Client IDE (I didn't manage to make it load)
 - ✅ GraphiQL IDE
 - ✅ GraphQL Code Generation
 - ✅ GraphQL Voyager
 - 🟩 GraphQL Module (working until providers (SvelteKit & injectors))
 - 🟦 GraphQL Scalar (didn't check yet)
 - ✅ DataLoader (maybe we could even improve modules so that the definitions are also in modules)
 - 🟦 Schema (didn't check)
 - 🟦 Automatic Persisted Queries (didn't check)
 
 I'll open individual issues to sort this out. I'm probably doing something wrong.
 Anyway, awesome job! 🎉
