### ISSUE TITLE
Ez vs Envelop plugins

### ISSUE THREAD

**Issue by RicardoValero95** [PabloSzx/graphql-ez#150]
I kinda understood ez uses envelop (a plugin system). 

There are some plugins like DataLoader and GraphQL Modules that do the same thing (or that's what I'm aware) and are in both plugin hubs.

What are the differences between ez and envelop plugins?

**Comment by PabloSzx** [comment]
__TLDR__: EZ Plugins often use the Envelop plugins under the hood, and they are most focused into the API Building process rather than execution, Envelop Plugins are for the execution of the API

The EZ Plugins work around the lifecycle of the API building process, In the section [How EZ Plugins work?](https://www.graphql-ez.com/docs/plugins/how-ez-plugins-work) I try to explain it (without much depth yet) in the diagram.

the EZ DataLoader plugin uses under the hood the Envelop DataLoader plugin, and adds an extra helper called "registerDataLoader" in the EZ App builder (the object that has the function "buildApp") that does all the logic and minimizes boilerplate, including useful TypeScript helpers that allows you to add the dataloader into the Context Type very quickly.

The GraphQL Modules EZ Plugins also uses the Envelop GraphQL Modules plugin, and adds an extra helper called "registerModule" that also minimizes boilerplate.


__GraphQL EZ__ still hasn't been officially released, and with that, all the docs are nowhere near perfect yet.

**Comment by RicardoValero95** [comment]
I get it now. I've been using GraphQL Ez for about two weeks because it is too easy (no pun intended) to setup. Previously, I used mercurius and mercurius-auth, I thought I'd wait for an ez plugin but I'll test out the generic-auth envelop plugin. 
Thanks, keep up the great work. 
Also are you opening the discussions tab or are you waiting for the release?

**Comment by PabloSzx** [comment]
I forgot to enable it, now we have discussions tab 👍
