### ISSUE TITLE
How to add custom context to graphql ez?

### ISSUE THREAD

**Issue by Unbuttun** [PabloSzx/graphql-ez#159]
Previously while using Apollo Server with Fastify, I did something like this for my context - 
```js
 const server = new ApolloServer({
    context: ({ request, reply }: AppContext) => ({
      redis,
      reply,
      request,
    }),
    schema
  });
```
And 
```js
export type AppContext = {
  req: FastifyRequest & { session: { userId: string } };
  res: FastifyReply;
  redis: Redis;
};
```

So that i was able to handle the session in my req.session.userId in my typegraphl setup.

Can you guide a bit on how can i achieve similar type of behaviour while using Graphl-ez?

**Comment by PabloSzx** [comment]
Here is the docs about it https://www.graphql-ez.com/docs/integrations/fastify#build-custom-context

**Comment by PabloSzx** [comment]
To use the session.userId you have to do module you have to use `declare module "fastify"` like the fastify docs mention https://www.fastify.io/docs/latest/TypeScript/#request, and to use them while you build context it's simply `fastify?.request.session?.userId`, the fastify specific object is optional since if you add for example "websockets", it will not have access to the fastify object, and only the HTTPs IncomingMessage

**Comment by Unbuttun** [comment]
Thanks for the help, this is how I fixed it.

```js
import { EZContext } from "graphql-ez";
const t = createTypesFactory<EZContext>();
```
I directly referenced the EZContext into my graphql schema generator and it started working.
