### ISSUE TITLE
Rerelease packages with fixed exports

### ISSUE THREAD

**Issue by benbender** [PabloSzx/graphql-ez#38]
Hey,

seems to be a quite interesting project you're working on here! And I would love to play with it ;) As I've noticed, you already fixed a bug about the (re-)exports of the packages. 
Would you mind to push a new release of the packages with those fixed exports so one don't have to fix those exports by hand in node_modules? Would be very much appreciated!

Thank you & best,

Ben

**Comment by PabloSzx** [comment]
Hi, it's nice to hear that there is already people using it and it hasn't even been announced yet, I will do the release with the fixes in #20, but keep in mind that `graphql-ez` is right now going through a considerable big refactor with a considerable amount of breaking changes (draft pr in #39), and making more stuff opt-in instead of opt-out that makes it more of a plugin-based "framework"/library, somewhat following some of the ideas of Envelop

**Comment by benbender** [comment]
Hey, no worries, I'm quite aware of the cute baby-age of the product. Give it time, let it grow ;)

Thanks for the quick response!
